sudo: required

language: python

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker network create --driver bridge meetup_loto_net
  - docker run -d -e 'ssl=true' --net=meetup_loto_net -v $(pwd)/tests/mock/meetup:/config -e 'custom_responses_config=/config/config.yml' --name api.meetup.com campanda/webserver-mock
script:
  - docker build --build-arg TRAVIS_JOB_ID=${TRAVIS_JOB_ID} --network meetup_loto_net -t ghibourg/meetup_loto .
after_success:
  - docker rm -f api.meetup.com
  - docker network rm meetup_loto_net
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push ghibourg/meetup_loto
