sudo: required

language: python

services:
  - docker

branches:
  only:
    - master

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
script:
  - docker build --build-arg TRAVIS_JOB_ID=${TRAVIS_JOB_ID} -t ghibourg/meetup_loto .
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push ghibourg/meetup_loto
